# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '2.7.2'

gem 'architect-functions', '~> 0.5.3'

gem "logger", "~> 1.4"

gem "aws-sdk", "~> 3.0"
